<?php

/**
 * Implements hook_menu().
 */
function mapbox_bridge_menu() {

  $items['admin/config/user-interface/mapbox_bridge'] = array(
    'title' => 'Mapbox Bridge',
    'description' => 'Configure Mapbox',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mapbox_bridge_admin_settings'),
    'access arguments' => array('administer'),
    'file' => 'mapbox_bridge.admin.inc',
  );

  return $items;
}

// will call all modules implementing hook_hook_name
module_invoke_all('hook_name');

function mapbox_bridge_render_map($map_id, $type) {

  // add the necessary js and css files from mapbox
  drupal_add_js('https://api.tiles.mapbox.com/mapbox.js/v2.1.7/mapbox.js', 'external');
  drupal_add_css('https://api.tiles.mapbox.com/mapbox.js/v2.1.7/mapbox.css', 'external');

  // pass the $map_id and token to the js
  drupal_add_js(array('mapboxBridge' => array(
    'mapId' => $map_id,
    'publicToken' => variable_get('mapbox_bridge_public', NULL)
  )), 'setting');

  // add the internal js file to launch mapbox
  drupal_add_js(drupal_get_path('module', 'mapbox_bridge') . '/js/mapbox_bridge.behaviours.js', array('group' => JS_LIBRARY, 'weight' => -1));

  // div that will contain the map
  return '<div class="mapbox-bridge mapbox-type-' . $type . '" id="map" style="width: 100%; height: 600px;"></div>';

}